[package]
name = "strata-merkle"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]
default = []
borsh = ["dep:borsh"]

[dependencies]
borsh = { workspace = true, optional = true }
digest.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
