[package]
name = "strata-mmr"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
borsh.workspace = true
digest.workspace = true
serde.workspace = true
sha2.workspace = true
thiserror.workspace = true
