[package]
name = "strata-l1-envelope-fmt"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
# Use txfmt without default features
strata-l1-txfmt = { path = "../txfmt", default-features = false }
strata-identifiers = { path = "../../identifiers", default-features = false }

tracing.workspace = true

bitcoin.workspace = true
thiserror.workspace = true

[features]
test-utils = []